#spring.jpa.properties.hibernate.jdbc.batch_size=20
spring:
 jpa:
   properties:
     hibernate:
       jdbc:
         batch_size: 20
 profiles.active: dev
 cloud:
   gcp:
     project-id: pnr-order-poc
     spanner:
       instance-id: instance-1
       database: database-1


 


## logging
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} [%X{source}] [%X{correlation-id}] [%-5level] [%C:%L] - %m%n'
  file: logs/spanner-pollar-convereter-publisher/app.log
  level.org.springframework: info

# actuator properties
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  info.git.mode: full

info:
  app:
    name: pnr-order-poc
    description: Google cloud spanner poller  
    version: 1.0.0
    java-vendor: ${java.specification.vendor}


---
spring.profiles: dev

---
spring.profiles: test

---
spring.profiles: prod